LTO_ENABLE = yes
BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = no
REPEAT_KEY_ENABLE = no
LAYER_LOCK_ENABLE = no
CAPS_WORD_ENABLE = no
BACKLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGBLIGHT_ENABLE = no
SWAP_HANDS_ENABLE = no
OLED_ENABLE = yes
WPM_ENABLE = yes
VIA_ENABLE = yes
VIAL_ENABLE = yes
ENCODER_ENABLE = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = no
KEY_OVERRIDE_ENABLE = no
QMK_SETTINGS = no
SLEEP_LED_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
OLED_FADE_OUT = yes
OLED_FADE_OUT_INTERVAL = 5
LUNA_ENABLE = yes

ifeq ($(strip $(OLED_ENABLE)), yes)
    SRC += lib/lily58_oled.c

    ifeq ($(strip $(LUNA_ENABLE)), yes)
        SRC += lib/luna.c
        OPT_DEFS += -DLUNA_ENABLE
    endif
endif
